version: '2'
services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - /data/sonarqube/extensions:/opt/sonarqube/extensions
      - /data/sonarqube/plugins:/opt/sonarqube/lib/bundled-plugins
      - /data/sonarqube/conf/sonar.properties:/opt/sonarqube/conf/sonar.properties
    networks:
      - front-tier
      - back-tier
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /data/sonarqube/postgres:/var/lib/postgresql
    networks:
      - back-tier
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
